In [1]:
import numpy as np

a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]).transpose()
mean_a = np.mean(a, 0)
print(a)
mean_a

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


array([2. , 8.4])

In [2]:
a = a - mean_a
a

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [3]:
a_centered_sp = np.dot(a[:, 0], a[:, 1])
a_centered_sp /= (np.shape(a)[0] - 1)
a_centered_sp

2.0

In [4]:
cov = np.cov([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
assert a_centered_sp == cov[0][1]
cov

array([[1. , 2. ],
       [2. , 4.3]])